//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stand_Automoveis
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarrosOficina : Carros
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarrosOficina()
        {
            this.Servico = new HashSet<Servicos>();
        }
    
        public string Matricula { get; set; }
        public string Kms { get; set; }
        public int ClienteIdCliente { get; set; }
    
        public virtual Clientes Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Servicos> Servico { get; set; }
    }
}
