//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Stand_Automoveis
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class StandLocalContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new StandLocalContainer object using the connection string found in the 'StandLocalContainer' section of the application configuration file.
        /// </summary>
        public StandLocalContainer() : base("name=StandLocalContainer", "StandLocalContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new StandLocalContainer object.
        /// </summary>
        public StandLocalContainer(string connectionString) : base(connectionString, "StandLocalContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new StandLocalContainer object.
        /// </summary>
        public StandLocalContainer(EntityConnection connection) : base(connection, "StandLocalContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
    }

    #endregion

}
