//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stand_Automoveis
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StandLocalDBContainer : DbContext
    {
        public StandLocalDBContainer()
            : base("name=StandLocalDBContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Carro> Carro { get; set; }
        public virtual DbSet<Parcela> Parcela { get; set; }
        public virtual DbSet<Servico> Servico { get; set; }
        public virtual DbSet<Venda> Vendas { get; set; }
        public virtual DbSet<Aluguer> Aluguer { get; set; }
    }
}
